version: "3"
services:

  mlflow:
    container_name: mlflow-server
    build:
      context: .
      args:
        MLFLOW_ARTIFACT_STORE: ${MLFLOW_ARTIFACT_STORE}
      dockerfile: ./docker/Dockerfile.server
    ports:
      - ${LOCAL_DEV_MLFLOW_SERVER_PORT}:${LOCAL_DEV_MLFLOW_SERVER_PORT}
    volumes:
      - ./mlflow:/mlflow
    env_file:
      - .envs/.mlflow-common
      - .envs/.mlflow-dev
    depends_on:
      - postgres

  experiments:
    container_name: experiments
    # image: docker.io/bitnami/mlflow:2
    build:
      context: .
      args:
        USER_NAME: "${USER_NAME:-atull}"
        USER_ID: "${USER_ID:-1232}"
      dockerfile: ./docker/Dockerfile.experiments
    volumes:
      - .:/experiments
    command: ["experiments/script.py"]
    env_file:
      - ./.envs/.experiments
    depends_on:
      - mlflow
    

  postgres:
    container_name: postgres-local
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .envs/.postgres