version: "3"
services:
  mlflow:
    container_name: mlflow-server
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/app
